name: session_list
author: Arnaud Kientz
email: arnaud@linuxmuster.net
url: https://ajenti.org
docs: https://docs.ajenti.org/en/latest/plugins/session_list.html
version: '0.4.0'
title: 'Session_list'
icon: hdd
requires-angular-build: true
frontend-settings:
    remote-entry: 'http://localhost:4204/remoteEntry.js' # For debug purposes. Keep empty for production!
    remote-name: 'session_list'
    exposed-module: './Module'
    display-name: 'Session_list'
    route-path: 'session_list'
    ng-module-name: 'Session_listModule'
dependencies:
    - !PluginDependency { plugin_name: core }
resources:
    - path: frontend/dist/vendor.js
      vendor: true
    - frontend/dist/polyfills.js
    - frontend/dist/runtime.js
    - frontend/dist/styles.css
    - frontend/dist/main.js
    - ng:ajenti.session_list
